# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lidar_interface\ui\SaveCsvWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveCsvWindow(object):
    def setupUi(self, SaveCsvWindow):
        SaveCsvWindow.setObjectName("SaveCsvWindow")
        SaveCsvWindow.resize(600, 300)
        self.label_title = QtWidgets.QLabel(SaveCsvWindow)
        self.label_title.setGeometry(QtCore.QRect(10, 20, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.progressBar = QtWidgets.QProgressBar(SaveCsvWindow)
        self.progressBar.setGeometry(QtCore.QRect(260, 230, 301, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.Label_lable = QtWidgets.QLabel(SaveCsvWindow)
        self.Label_lable.setGeometry(QtCore.QRect(260, 60, 60, 16))
        self.Label_lable.setObjectName("Label_lable")
        self.List_pose = QtWidgets.QListWidget(SaveCsvWindow)
        self.List_pose.setGeometry(QtCore.QRect(20, 50, 201, 181))
        self.List_pose.setObjectName("List_pose")
        self.Button_back = QtWidgets.QPushButton(SaveCsvWindow)
        self.Button_back.setGeometry(QtCore.QRect(10, 260, 82, 25))
        self.Button_back.setObjectName("Button_back")
        self.FunLabel_selectedpose = QtWidgets.QLabel(SaveCsvWindow)
        self.FunLabel_selectedpose.setGeometry(QtCore.QRect(320, 60, 101, 16))
        self.FunLabel_selectedpose.setObjectName("FunLabel_selectedpose")
        self.Label_frames = QtWidgets.QLabel(SaveCsvWindow)
        self.Label_frames.setGeometry(QtCore.QRect(260, 90, 60, 16))
        self.Label_frames.setObjectName("Label_frames")
        self.Input_frames = QtWidgets.QLineEdit(SaveCsvWindow)
        self.Input_frames.setGeometry(QtCore.QRect(320, 90, 101, 20))
        self.Input_frames.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Input_frames.setObjectName("Input_frames")
        self.Label_name = QtWidgets.QLabel(SaveCsvWindow)
        self.Label_name.setGeometry(QtCore.QRect(260, 120, 60, 16))
        self.Label_name.setObjectName("Label_name")
        self.Input_name = QtWidgets.QLineEdit(SaveCsvWindow)
        self.Input_name.setGeometry(QtCore.QRect(320, 120, 101, 20))
        self.Input_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Input_name.setObjectName("Input_name")
        self.Button_countforsequence = QtWidgets.QPushButton(SaveCsvWindow)
        self.Button_countforsequence.setGeometry(QtCore.QRect(440, 50, 151, 161))
        self.Button_countforsequence.setAutoFillBackground(False)
        self.Button_countforsequence.setObjectName("Button_countforsequence")
        self.Label_saveformat = QtWidgets.QLabel(SaveCsvWindow)
        self.Label_saveformat.setGeometry(QtCore.QRect(190, 260, 371, 20))
        self.Label_saveformat.setObjectName("Label_saveformat")
        self.Button_adjust = QtWidgets.QPushButton(SaveCsvWindow)
        self.Button_adjust.setGeometry(QtCore.QRect(290, 150, 91, 25))
        self.Button_adjust.setObjectName("Button_adjust")
        self.Button_start = QtWidgets.QPushButton(SaveCsvWindow)
        self.Button_start.setGeometry(QtCore.QRect(330, 190, 91, 25))
        self.Button_start.setStyleSheet("background-color: rgb(184, 255, 184);")
        self.Button_start.setObjectName("Button_start")
        self.Button_stop = QtWidgets.QPushButton(SaveCsvWindow)
        self.Button_stop.setGeometry(QtCore.QRect(230, 190, 91, 25))
        self.Button_stop.setStyleSheet("background-color: rgb(255, 186, 174);")
        self.Button_stop.setObjectName("Button_stop")
        self.Label_Count = QtWidgets.QLabel(SaveCsvWindow)
        self.Label_Count.setGeometry(QtCore.QRect(460, 20, 41, 16))
        self.Label_Count.setObjectName("Label_Count")
        self.FuncLabel_count = QtWidgets.QLabel(SaveCsvWindow)
        self.FuncLabel_count.setGeometry(QtCore.QRect(510, 20, 41, 16))
        self.FuncLabel_count.setObjectName("FuncLabel_count")

        self.retranslateUi(SaveCsvWindow)
        QtCore.QMetaObject.connectSlotsByName(SaveCsvWindow)

    def retranslateUi(self, SaveCsvWindow):
        _translate = QtCore.QCoreApplication.translate
        SaveCsvWindow.setWindowTitle(_translate("SaveCsvWindow", "SaveCsvWindow"))
        self.label_title.setText(_translate("SaveCsvWindow", "Save to CSV - Select the pose"))
        self.Label_lable.setText(_translate("SaveCsvWindow", "pose : "))
        self.Button_back.setText(_translate("SaveCsvWindow", "Back"))
        self.FunLabel_selectedpose.setText(_translate("SaveCsvWindow", "None"))
        self.Label_frames.setText(_translate("SaveCsvWindow", "Frames:"))
        self.Input_frames.setText(_translate("SaveCsvWindow", "500"))
        self.Label_name.setText(_translate("SaveCsvWindow", "Name:"))
        self.Input_name.setText(_translate("SaveCsvWindow", "default"))
        self.Button_countforsequence.setText(_translate("SaveCsvWindow", "Count for Sequence"))
        self.Label_saveformat.setText(_translate("SaveCsvWindow", "save format : <label Name>_<Name>_<Frames><Date>.csv"))
        self.Button_adjust.setText(_translate("SaveCsvWindow", "Adjust"))
        self.Button_start.setText(_translate("SaveCsvWindow", "Start"))
        self.Button_stop.setText(_translate("SaveCsvWindow", "Stop"))
        self.Label_Count.setText(_translate("SaveCsvWindow", "Count"))
        self.FuncLabel_count.setText(_translate("SaveCsvWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaveCsvWindow = QtWidgets.QWidget()
    ui = Ui_SaveCsvWindow()
    ui.setupUi(SaveCsvWindow)
    SaveCsvWindow.show()
    sys.exit(app.exec_())
