# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lidar_interface\ui\SkeletonViewWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SkeletonViewWindow(object):
    def setupUi(self, SkeletonViewWindow):
        SkeletonViewWindow.setObjectName("SkeletonViewWindow")
        SkeletonViewWindow.resize(830, 725)
        self.label_title = QtWidgets.QLabel(SkeletonViewWindow)
        self.label_title.setGeometry(QtCore.QRect(10, 20, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.Button_back = QtWidgets.QPushButton(SkeletonViewWindow)
        self.Button_back.setGeometry(QtCore.QRect(30, 680, 82, 25))
        self.Button_back.setObjectName("Button_back")
        self.Button_start = QtWidgets.QPushButton(SkeletonViewWindow)
        self.Button_start.setGeometry(QtCore.QRect(150, 680, 91, 25))
        self.Button_start.setObjectName("Button_start")
        self.Button_stop = QtWidgets.QPushButton(SkeletonViewWindow)
        self.Button_stop.setGeometry(QtCore.QRect(270, 680, 91, 25))
        self.Button_stop.setObjectName("Button_stop")
        self.verticalLayoutWidget = QtWidgets.QWidget(SkeletonViewWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 50, 561, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(SkeletonViewWindow)
        QtCore.QMetaObject.connectSlotsByName(SkeletonViewWindow)

    def retranslateUi(self, SkeletonViewWindow):
        _translate = QtCore.QCoreApplication.translate
        SkeletonViewWindow.setWindowTitle(_translate("SkeletonViewWindow", "SkeletonViewWindow"))
        self.label_title.setText(_translate("SkeletonViewWindow", "3D View"))
        self.Button_back.setText(_translate("SkeletonViewWindow", "Back"))
        self.Button_start.setText(_translate("SkeletonViewWindow", "Start"))
        self.Button_stop.setText(_translate("SkeletonViewWindow", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SkeletonViewWindow = QtWidgets.QWidget()
    ui = Ui_SkeletonViewWindow()
    ui.setupUi(SkeletonViewWindow)
    SkeletonViewWindow.show()
    sys.exit(app.exec_())
